function [ PhaseFreq ] = FindOfPhase( AutoCorr, Nfft, PositionTs1 )
    for k =1 : fix((length(AutoCorr) + Nfft + Nfft/16)/ (Nfft + Nfft/8)) - 1
        PhaseFreq(k) = sum(...
                angle(...
                    AutoCorr(...
                        (k-1)*(Nfft + Nfft/8) + PositionTs1 - Nfft/64 : ...
                        (k-1)*(Nfft + Nfft/8) + PositionTs1 + Nfft/64))/...
                        (2*pi))/(Nfft/32);
    end
    PhaseFreq = sum(PhaseFreq(:))/...
        (fix((length(AutoCorr) + Nfft + Nfft/16)/ (Nfft + Nfft/8))-1);
end